# Generated by Django 4.2.6 on 2023-10-29 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='Team',
            new_name='team',
        ),
    ]
