# Generated by Django 4.2.6 on 2023-10-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_team_membership_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='link',
            field=models.URLField(max_length=300),
        ),
    ]
