# Generated by Django 4.2.6 on 2023-10-30 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_meeting_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_level', to='main.team'),
        ),
    ]
