# Generated by Django 4.2.6 on 2023-10-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_task_task_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='is_graded',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='attached',
            field=models.FileField(blank=True, null=True, upload_to='main/task_attachments/% Y/% m/% d/'),
        ),
    ]
